### ISSUE TITLE
L1 Mastering Font checklist

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fuzzy-bubbles#3]
### L1 Mastering Font checklist

**Diacritics**
- [ ] Inspect the font and choose the best version of the diacritics (in terms of balance, weight, size, contrast) and move them to comb mark.
- [ ] Adjust left and right sidebearings of all the comb marks to 0.
- [ ] Work on the selected diacritics to ensure the balance among all marks (contrast, weight, size, stroke or others)
- [ ] Ensure the consistence among related marks, [see issue of reference](https://github.com/googlefonts/italianno/issues/6).
- [ ] Adjust position, weight, or outlines of the diacritics if needed to, without changing the design of them, and using glyphs app locked guidelines.
- [ ] Decomposed transformed components, review proportions ensuring there are round coordinates.
- [ ] Test the comb marks by inspecting all of them in context (right-click and choose all glyphs using this component).
- [ ] Inspect and balance the below marks (size, weight, balance) e.g. `ogonek` `cedilla` to avoid huge marks
- [ ] Create [Catalan Punt Volat ](https://glyphsapp.com/learn/localize-your-font-catalan-punt-volat)
- [ ] Delete the legacy marks and add them back so they are made from comb marks.
- [ ] Create comb.case marks by making them less tall and less narrow while keeping them at the same weight (preferable at the height they are intended to use, to be able to inspect them in their context)
- [ ] Create the Vietnamese mark.
- [ ] Make compound glyphs for the entire font.
- [ ] Adjust the anchor position.
- [ ] Run the automatic Glyphsapp command: update glyph info.

**Glyphs & Outlines**
- [ ] Create the missing glyphs needed.
- [ ] Run the automatic Glyphsapp commands: Add extremes; cubic curves; correct outlines direction; tidy up paths; round coordinates; remove PS Hint
- [ ] Check kerning and spacing by using the txt files. Fix any kerning and spacing errors if needed for the most common kerning pairs.
- [ ] Check terminal forms spacing avoids crashes or collisions. [Issue of reference](https://github.com/googlefonts/comforter/issues/7)
- [ ] Run the automatic Glyphsapp command: `Resolve all metrics` to update the metrics in the entire font.
- [ ] Check everything once again by going glyph by glyph.
- [ ] Run the automatic Glyphsapp `Update Glyph Info` command to avoid bad names issues
- [ ] Run the automatic Glyphsapp `Convert to cubic` command to avoid qcurves
- [ ] `@` `¿?` `¡!` `””` position, spacing is good

**OT Features**
- [ ] Check OpenType features and see if all listed are valid, e.g. if `.fina` glyphs are actually ending shapes or ss are not repeated under different names.
- [ ] Create Lookup for positional alternates for `fina` and `init` cases
- [ ] Inspect if Stylistic Sets have the right name or rename .001 etc... glyphs and generate the automatic OpenType code.
- [ ] Check if there is a stylistic set that would correspond to `SmallCaps` feature instead and change it.
- [ ] Check if the OpenType code has any error.
- [ ] Hit the `update` & `compile` buttons to check everything is working well.

**Testing changes**
- [ ] Inspect the font created by the CI GHA to check production errors. If the action isn't included yet in the repo, export and test the font using Glyphs.
- [ ] Check the before and after font using `gen-html diff` if needed (for update font cases)
- [ ] Check the font on `gen-html proof` to see if it's working well on web. Use the `--imgs` flag to produce images.
- [ ] Commit and make PR using images.
